/**
 * Cadastro Oficial de Empresas e Departamentos
 * Conforme tabelas do sistema financeiro Dealer / SiTef
 */

export const CADASTRO_EMPRESAS: string[] = [
  'BYD - ARRUDA',
  'BYD - CAMINHO DAS ARVORES',
  'BYD - WASHINGTON SOARES',
  'GEELY MADALENA',
  'GEELY ACM',
  'GEELY IMBIRIBEIRA',
  'GEELY IGUATEMI - OFICINA',
  'RENAULT EPITACIO PESSOA',
  'RENAULT CABEDELO',
  'GEELY ANTO. GAMA CTA - OFICINA',
  'GEELY EPITACIO PESSOA',
  'NISSAN PIEDADE COMPLEXO',
  'RENAULT ANTONIO GAMA CTA',
  'FORD CARUARU',
  'FORD IMBIRIBEIRA',
  'KIA IMBIRIBEIRA',
  'CJDR ACM',
  'JEEP DUNAS',
  'JEEP IMBIRIBEIRA',
  'JEEP JABOATAO',
  'JEEP PARQUELANDIA',
  'JEEP RIO VERMELHO',
  'NEWVIA BONOCO',
  'NEWVIA CARUARU',
  'NEWVIA IMBIRIBEIRA',
  'NEWVIA LAURO',
  'NEWVIA WASH. SOARES',
  'NEWVIA PIEDADE',
  'NEWVIA PARQUELANDIA',
  'NISSAN AFOGADOS',
  'NISSAN CAXANGA',
  'NISSAN IGUATEMI',
  'NISSAN IMBIRIBEIRA',
  'NISSAN LAURO',
  'NISSAN PARALELA',
  'NISSAN RIO VERMELHO',
  'OMODA ABDIAS',
  'OMODA ALDEOTA',
  'OMODA PARALELA',
  'RENAULT AFOGADOS',
  'RENAULT IGUATEMI',
  'RENAULT IMBIRIBEIRA',
  'RENAULT IMBIRIBEIRA SEMINOVOS',
  'RENAULT LAURO',
  'RENAULT OLINDA',
  'RENAULT PIEDADE',
  'RENAULT PRADO SEMINOVOS',
  'LEAP IMBIRIBEIRA',
  'VIA SUL ARRUDA',
  'VIA SUL AV. NORTE SEMINOVOS',
  'VIA SUL DUNAS',
  'VIA SUL MATRIZ',
];

export const EMPRESAS_ALIASES_MAP: Record<string, string> = {
  // BYD
  'BYD ARRUDA': 'BYD - ARRUDA',
  'BYD - ARRUDA': 'BYD - ARRUDA',
  'BYD CAMINHO DAS ARVORES': 'BYD - CAMINHO DAS ARVORES',
  'BYD CAMINHO ARVORES': 'BYD - CAMINHO DAS ARVORES',
  'BYD C ARVORES': 'BYD - CAMINHO DAS ARVORES',
  'BYD C. ARVORES': 'BYD - CAMINHO DAS ARVORES',
  'BYD ARVORES': 'BYD - CAMINHO DAS ARVORES',
  'BYD - CAMINHO DAS ARVORES': 'BYD - CAMINHO DAS ARVORES',
  'BYD W SOARES': 'BYD - WASHINGTON SOARES',
  'BYD W. SOARES': 'BYD - WASHINGTON SOARES',
  'BYD WASH SOARES': 'BYD - WASHINGTON SOARES',
  'BYD WASH. SOARES': 'BYD - WASHINGTON SOARES',
  'BYD WASHINGTON SOARES': 'BYD - WASHINGTON SOARES',
  'BYD WASHINGTON': 'BYD - WASHINGTON SOARES',
  'BYD - WASHINGTON SOARES': 'BYD - WASHINGTON SOARES',

  // EUROVIA -> GEELY / RENAULT / NISSAN
  'EUROVIA AUTO LTDA': 'GEELY MADALENA',
  'EUROVIA AUTO': 'GEELY MADALENA',
  'EUROVIA AUTO LTDA.': 'GEELY MADALENA',
  'EUROVIA MADALENA': 'GEELY MADALENA',
  'EUROVIA AUTO LTDA - GEELY ACM': 'GEELY ACM',
  'EUROVIA AUTO LTDA GEELY ACM': 'GEELY ACM',
  'EUROVIA GEELY ACM': 'GEELY ACM',
  'EUROVIA AUTO LTDA - GEELY IMBIRIBEIRA': 'GEELY IMBIRIBEIRA',
  'EUROVIA AUTO LTDA GEELY IMBIRIBEIRA': 'GEELY IMBIRIBEIRA',
  'EUROVIA GEELY IMBIRIBEIRA': 'GEELY IMBIRIBEIRA',
  'EUROVIA AUTO LTDA - GEELY OFICINA': 'GEELY IGUATEMI - OFICINA',
  'EUROVIA AUTO LTDA GEELY OFICINA': 'GEELY IGUATEMI - OFICINA',
  'EUROVIA GEELY OFICINA': 'GEELY IGUATEMI - OFICINA',
  'EUROVIA EPITACIO PESSOA': 'RENAULT EPITACIO PESSOA',
  'EUROVIA EPITACIO': 'RENAULT EPITACIO PESSOA',
  'EUROVIA FILIAL CABEDELO': 'RENAULT CABEDELO',
  'EUROVIA CABEDELO': 'RENAULT CABEDELO',
  'EUROVIA GEELY PB ANT. GA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'EUROVIA GEELY PB ANT GA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'EUROVIA GEELY PB ANTO GA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'EUROVIA GEELY PB ANTONIO GAMA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'EUROVIA GEELY PB EPITACIO': 'GEELY EPITACIO PESSOA',
  'EUROVIA GEELY PB EPITACIO PESSOA': 'GEELY EPITACIO PESSOA',
  'EUROVIA NISSAN PIEDADE': 'NISSAN PIEDADE COMPLEXO',
  'EUROVIA VEICULOS S/A CTA': 'RENAULT ANTONIO GAMA CTA',
  'EUROVIA VEICULOS SA CTA': 'RENAULT ANTONIO GAMA CTA',
  'EUROVIA VEICULOS S/A - CTA': 'RENAULT ANTONIO GAMA CTA',
  'EUROVIA CTA': 'RENAULT ANTONIO GAMA CTA',

  // GRANVIA & INTERVIA
  'GRANVIA CARUARU': 'FORD CARUARU',
  'GRANVIA IMBIRIBEIRA': 'FORD IMBIRIBEIRA',
  'INTERVIA IMBIRIBEIRA': 'KIA IMBIRIBEIRA',

  // JEEP / CJDR
  'JEEP ACM': 'CJDR ACM',
  'CJDR': 'CJDR ACM',
  'CJDR ACM': 'CJDR ACM',
  'CJDR - ACM': 'CJDR ACM',
  'JEEP DUNAS': 'JEEP DUNAS',
  'JEEP IMBIRIBEIRA': 'JEEP IMBIRIBEIRA',
  'JEEP JABOATAO': 'JEEP JABOATAO',
  'JEEP JABOATÃO': 'JEEP JABOATAO',
  'JEEP PARQUELANDIA': 'JEEP PARQUELANDIA',
  'JEEP PARQUELÂNDIA': 'JEEP PARQUELANDIA',
  'JEEP RIO VERMELHO': 'JEEP RIO VERMELHO',

  // GEELY
  'GEELY MADALENA': 'GEELY MADALENA',
  'GEELY ACM': 'GEELY ACM',
  'GEELY IMBIRIBEIRA': 'GEELY IMBIRIBEIRA',
  'GEELY IGUATEMI': 'GEELY IGUATEMI - OFICINA',
  'GEELY IGUATEMI OFICINA': 'GEELY IGUATEMI - OFICINA',
  'GEELY IGUATEMI - OFICINA': 'GEELY IGUATEMI - OFICINA',
  'GEELY ANTO GAMA CTA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'GEELY ANTO. GAMA CTA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'GEELY ANTONIO GAMA CTA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'GEELY ANTO GAMA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'GEELY ANTO. GAMA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'GEELY ANTONIO GAMA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'GEELY CTA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'GEELY ANTO. GAMA CTA - OFICINA': 'GEELY ANTO. GAMA CTA - OFICINA',
  'GEELY EPITACIO PESSOA': 'GEELY EPITACIO PESSOA',
  'GEELY EPITACIO': 'GEELY EPITACIO PESSOA',

  // RENAULT
  'RENAULT EPITACIO PESSOA': 'RENAULT EPITACIO PESSOA',
  'RENAULT EPITACIO': 'RENAULT EPITACIO PESSOA',
  'RENAULT CABEDELO': 'RENAULT CABEDELO',
  'RENAULT ANTONIO GAMA CTA': 'RENAULT ANTONIO GAMA CTA',
  'RENAULT ANTO. GAMA CTA': 'RENAULT ANTONIO GAMA CTA',
  'RENAULT ANTO GAMA CTA': 'RENAULT ANTONIO GAMA CTA',
  'RENAULT ANTONIO GAMA': 'RENAULT ANTONIO GAMA CTA',
  'RENAULT ANTO GAMA': 'RENAULT ANTONIO GAMA CTA',
  'RENAULT AFOGADOS': 'RENAULT AFOGADOS',
  'RENAULT IGUATEMI': 'RENAULT IGUATEMI',
  'RENAULT IMBIRIBEIRA': 'RENAULT IMBIRIBEIRA',
  'RENAULT IMBIRIBEIRA SEMINOVOS': 'RENAULT IMBIRIBEIRA SEMINOVOS',
  'RENAULT IMBIRIBEIRA SEMI': 'RENAULT IMBIRIBEIRA SEMINOVOS',
  'RENAULT LAURO': 'RENAULT LAURO',
  'RENAULT OLINDA': 'RENAULT OLINDA',
  'RENAULT PIEDADE': 'RENAULT PIEDADE',
  'RENAULT PRADO SEMINOVOS': 'RENAULT PRADO SEMINOVOS',
  'RENAULT PRADO': 'RENAULT PRADO SEMINOVOS',

  // NISSAN
  'NISSAN PIEDADE COMPLEXO': 'NISSAN PIEDADE COMPLEXO',
  'NISSAN PIEDADE': 'NISSAN PIEDADE COMPLEXO',
  'NISSAN COMPLEXO PIEDADE': 'NISSAN PIEDADE COMPLEXO',
  'NISSAN AFOGADOS': 'NISSAN AFOGADOS',
  'NISSAN CAXANGA': 'NISSAN CAXANGA',
  'NISSAN CAXANGÁ': 'NISSAN CAXANGA',
  'NISSAN IGUATEMI': 'NISSAN IGUATEMI',
  'NISSAN IMBIRIBEIRA': 'NISSAN IMBIRIBEIRA',
  'NISSAN LAURO': 'NISSAN LAURO',
  'NISSAN PARALELA': 'NISSAN PARALELA',
  'NISSAN RIO VERMELHO': 'NISSAN RIO VERMELHO',

  // FORD & KIA
  'FORD CARUARU': 'FORD CARUARU',
  'FORD IMBIRIBEIRA': 'FORD IMBIRIBEIRA',
  'KIA IMBIRIBEIRA': 'KIA IMBIRIBEIRA',

  // NEWVIA
  'NEWVIA BONOCO': 'NEWVIA BONOCO',
  'NEWVIA CARUARU': 'NEWVIA CARUARU',
  'NEWVIA IMBIRIBEIRA': 'NEWVIA IMBIRIBEIRA',
  'NEWVIA LAURO': 'NEWVIA LAURO',
  'NEWVIA MOTOS CAMBEBA': 'NEWVIA WASH. SOARES',
  'NEWVIA CAMBEBA': 'NEWVIA WASH. SOARES',
  'NEWVIA MOTOS LTDA': 'NEWVIA PIEDADE',
  'NEWVIA MOTOS PARQUELANDI': 'NEWVIA PARQUELANDIA',
  'NEWVIA MOTOS PARQUELANDIA': 'NEWVIA PARQUELANDIA',
  'NEWVIA WASH. SOARES': 'NEWVIA WASH. SOARES',
  'NEWVIA WASH SOARES': 'NEWVIA WASH. SOARES',
  'NEWVIA W SOARES': 'NEWVIA WASH. SOARES',
  'NEWVIA W. SOARES': 'NEWVIA WASH. SOARES',
  'NEWVIA WASHINGTON SOARES': 'NEWVIA WASH. SOARES',
  'NEWVIA PIEDADE': 'NEWVIA PIEDADE',
  'NEWVIA PARQUELANDIA': 'NEWVIA PARQUELANDIA',
  'NEWVIA PARQUELÂNDIA': 'NEWVIA PARQUELANDIA',

  // OMODA & LEAP
  'OMODA ABDIAS': 'OMODA ABDIAS',
  'OMODA ALDEOTA': 'OMODA ALDEOTA',
  'OMODA PARALELA': 'OMODA PARALELA',
  'VIA SUL VEICULOS S/A - LEAP IMBIRIBEIRA': 'LEAP IMBIRIBEIRA',
  'VIA SUL VEICULOS SA LEAP IMBIRIBEIRA': 'LEAP IMBIRIBEIRA',
  'VIA SUL LEAP IMBIRIBEIRA': 'LEAP IMBIRIBEIRA',
  'LEAP IMBIRIBEIRA': 'LEAP IMBIRIBEIRA',

  // VIA SUL
  'VIASUL ARRUDA': 'VIA SUL ARRUDA',
  'VIA SUL ARRUDA': 'VIA SUL ARRUDA',
  'VIASUL AV NORTE': 'VIA SUL AV. NORTE SEMINOVOS',
  'VIASUL AV. NORTE': 'VIA SUL AV. NORTE SEMINOVOS',
  'VIASUL AV NORTE SEMINOVOS': 'VIA SUL AV. NORTE SEMINOVOS',
  'VIA SUL AV. NORTE SEMINOVOS': 'VIA SUL AV. NORTE SEMINOVOS',
  'VIA SUL AV NORTE SEMINOVOS': 'VIA SUL AV. NORTE SEMINOVOS',
  'VIA SUL AV. NORTE': 'VIA SUL AV. NORTE SEMINOVOS',
  'VIA SUL AV NORTE': 'VIA SUL AV. NORTE SEMINOVOS',
  'VIA SUL AVENIDA NORTE': 'VIA SUL AV. NORTE SEMINOVOS',
  'VIASUL DUNAS': 'VIA SUL DUNAS',
  'VIA SUL DUNAS': 'VIA SUL DUNAS',
  'VIASUL MATRIZ': 'VIA SUL MATRIZ',
  'VIA SUL MATRIZ': 'VIA SUL MATRIZ',
};

export const CADASTRO_DEPARTAMENTOS: string[] = [
  '30129-CAIXA LOJA - DEPTO.OFICINA',
  '30132-CAIXA LOJA - DEPTO. SEMINOVOS',
  '30133-CAIXA LOJA - DEPTO. V. NOVOS',
  '30135-CAIXA LOJA - DEPTO. PEÇAS',
  '30138-CAIXA LOJA - DEPARTAMENTO FUNILARIA',
];

export const CADASTRO_CONTAS_GERENCIAIS: string[] = [
  '30129-CAIXA LOJA - DEPTO.OFICINA',
  '30132-CAIXA LOJA - DEPTO. SEMINOVOS',
  '30133-CAIXA LOJA - DEPTO. V. NOVOS',
  '30135-CAIXA LOJA - DEPTO. PEÇAS',
  '30138-CAIXA LOJA - DEPARTAMENTO FUNILARIA',
];

/**
 * Verifica se um cabeçalho de coluna refere-se a Empresa / Filial / Loja
 */
export function isEmpresaColumn(headerName: string): boolean {
  if (!headerName) return false;
  const norm = headerName
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
  return (
    norm.includes('empresa') ||
    norm.includes('filial') ||
    norm.includes('loja') ||
    norm.includes('unidade') ||
    norm.includes('concessionaria')
  );
}

/**
 * Verifica se um cabeçalho de coluna refere-se a Departamento / Depto / Setor
 */
export function isDepartamentoColumn(headerName: string): boolean {
  if (!headerName) return false;
  const norm = headerName
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
  return (
    norm.includes('departamento') ||
    norm.includes('depto') ||
    norm.includes('setor') ||
    norm.includes('dep.') ||
    norm.includes('centro de custo')
  );
}

/**
 * Verifica se um cabeçalho de coluna refere-se a Conta Gerencial
 */
export function isContaGerencialColumn(headerName: string): boolean {
  if (!headerName) return false;
  const norm = headerName
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
  return (
    norm.includes('conta gerencial') ||
    norm.includes('conta_gerencial') ||
    norm.includes('cta gerencial') ||
    norm.includes('cta. gerencial') ||
    norm.includes('cta_gerencial') ||
    norm.includes('plano de contas') ||
    (norm.includes('conta') && !norm.includes('contato'))
  );
}

/**
 * Verifica se um cabeçalho de coluna refere-se a Data / Data do Cx
 */
export function isDateColumn(headerName: string): boolean {
  if (!headerName) return false;
  const norm = headerName
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
  return (
    norm.includes('data') ||
    norm.includes('dt_') ||
    norm.includes('dt ') ||
    norm.includes('cx') ||
    norm.includes('caixa') ||
    norm.includes('date') ||
    norm.includes('periodo') ||
    norm.includes('emissao') ||
    norm.includes('vencimento')
  );
}

/**
 * Converte data em formato DD/MM/AAAA para YYYY-MM-DD (para <input type="date">)
 */
export function toInputDateFormat(dateStr: string): string {
  if (!dateStr) return new Date().toISOString().split('T')[0];
  const trimmed = dateStr.trim();
  if (/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) {
    return trimmed;
  }
  const parts = trimmed.split(/[/.-]/);
  if (parts.length === 3) {
    if (parts[0].length <= 2 && parts[2].length === 4) {
      const d = parts[0].padStart(2, '0');
      const m = parts[1].padStart(2, '0');
      const y = parts[2];
      return `${y}-${m}-${d}`;
    }
  }
  return new Date().toISOString().split('T')[0];
}

/**
 * Converte YYYY-MM-DD para DD/MM/AAAA
 */
export function toDisplayDateFormat(isoDateStr: string): string {
  if (!isoDateStr) return new Date().toLocaleDateString('pt-BR');
  if (/^\d{2}\/\d{2}\/\d{4}$/.test(isoDateStr)) return isoDateStr;
  const parts = isoDateStr.split('-');
  if (parts.length === 3 && parts[0].length === 4) {
    const [y, m, d] = parts;
    return `${d.padStart(2, '0')}/${m.padStart(2, '0')}/${y}`;
  }
  return isoDateStr;
}
